package com.zilehasnain.qazatracker.domain.model

import com.zilehasnain.qazatracker.domain.model.PrayerCalculationMethod.EGYPTIAN
import com.zilehasnain.qazatracker.domain.model.PrayerCalculationMethod.GULF
import com.zilehasnain.qazatracker.domain.model.PrayerCalculationMethod.ISNA
import com.zilehasnain.qazatracker.domain.model.PrayerCalculationMethod.JAFARI
import com.zilehasnain.qazatracker.domain.model.PrayerCalculationMethod.KARACHI
import com.zilehasnain.qazatracker.domain.model.PrayerCalculationMethod.MIQAT
import com.zilehasnain.qazatracker.domain.model.PrayerCalculationMethod.MWL
import com.zilehasnain.qazatracker.domain.model.PrayerCalculationMethod.TEHRAN

/** Every country the finder knows about, with a suggested method. Plain data, no logic. */
object RegionCatalog {

    private const val HIGH_LATITUDE = "Far-northern summers may need a high-latitude rule."

    private fun r(
        code: String,
        name: String,
        method: PrayerCalculationMethod,
        vararg alternatives: PrayerCalculationMethod,
        hanafi: Boolean = false,
        note: String? = null
    ) = RegionInfo(code, name, method, alternatives.toList(), hanafi, note)

    val all: List<RegionInfo> = listOf(
        // South Asia
        r("PK", "Pakistan", KARACHI, MWL, hanafi = true),
        r("IN", "India", KARACHI, ISNA, MWL, hanafi = true, note = "Practice differs between communities."),
        r("BD", "Bangladesh", KARACHI, MWL, hanafi = true),
        r("AF", "Afghanistan", KARACHI, MWL, hanafi = true),
        r("LK", "Sri Lanka", KARACHI, MWL),
        r("NP", "Nepal", KARACHI, MWL, hanafi = true),
        r("BT", "Bhutan", KARACHI, MWL),
        r("MV", "Maldives", KARACHI, MWL),
        // Middle East and Gulf
        r("SA", "Saudi Arabia", GULF, MWL),
        r("AE", "United Arab Emirates", GULF, MWL),
        r("QA", "Qatar", GULF, MWL),
        r("KW", "Kuwait", GULF, MWL),
        r("BH", "Bahrain", GULF, MWL),
        r("OM", "Oman", GULF, MWL),
        r("YE", "Yemen", GULF, MWL, EGYPTIAN),
        r("IQ", "Iraq", JAFARI, MWL, EGYPTIAN),
        r("IR", "Iran", TEHRAN, JAFARI, MWL),
        r("JO", "Jordan", MWL, EGYPTIAN, GULF),
        r("LB", "Lebanon", MWL, EGYPTIAN, JAFARI),
        r("SY", "Syria", MWL, EGYPTIAN),
        r("PS", "Palestine", MWL, EGYPTIAN),
        r("IL", "Israel", MWL, EGYPTIAN),
        r("TR", "Turkey", MWL, EGYPTIAN, hanafi = true, note = "Diyanet publishes the official timetable."),
        r("CY", "Cyprus", MWL, EGYPTIAN),
        // North Africa
        r("EG", "Egypt", EGYPTIAN, MWL),
        r("LY", "Libya", EGYPTIAN, MWL),
        r("SD", "Sudan", EGYPTIAN, MWL),
        r("SS", "South Sudan", EGYPTIAN, MWL),
        r("TN", "Tunisia", MWL, EGYPTIAN),
        r("DZ", "Algeria", MWL, EGYPTIAN),
        r("MA", "Morocco", MWL, EGYPTIAN),
        r("EH", "Western Sahara", MWL, EGYPTIAN),
        r("MR", "Mauritania", MWL, EGYPTIAN),
        // Southeast and East Asia
        r("ID", "Indonesia", MIQAT, MWL, KARACHI),
        r("MY", "Malaysia", MIQAT, MWL),
        r("SG", "Singapore", MIQAT, MWL),
        r("BN", "Brunei", MIQAT, MWL),
        r("TH", "Thailand", MIQAT, MWL),
        r("PH", "Philippines", MIQAT, MWL),
        r("VN", "Vietnam", MIQAT, MWL),
        r("KH", "Cambodia", MIQAT, MWL),
        r("MM", "Myanmar", MIQAT, KARACHI),
        r("LA", "Laos", MIQAT, MWL),
        r("TL", "Timor-Leste", MIQAT, MWL),
        r("CN", "China", MWL, KARACHI, hanafi = true),
        r("JP", "Japan", MWL, ISNA),
        r("KR", "South Korea", MWL, ISNA),
        r("KP", "North Korea", MWL),
        r("MN", "Mongolia", MWL, KARACHI),
        r("TW", "Taiwan", MWL, ISNA),
        r("HK", "Hong Kong", MWL, ISNA),
        r("MO", "Macao", MWL),
        // Central Asia and the Caucasus
        r("KZ", "Kazakhstan", MWL, KARACHI, hanafi = true),
        r("UZ", "Uzbekistan", MWL, KARACHI, hanafi = true),
        r("TM", "Turkmenistan", MWL, KARACHI, hanafi = true),
        r("KG", "Kyrgyzstan", MWL, KARACHI, hanafi = true),
        r("TJ", "Tajikistan", MWL, KARACHI, hanafi = true),
        r("AZ", "Azerbaijan", MWL, JAFARI),
        r("AM", "Armenia", MWL),
        r("GE", "Georgia", MWL),
        // North America
        r("US", "United States", ISNA, MWL),
        r("CA", "Canada", ISNA, MWL),
        r("MX", "Mexico", ISNA, MWL),
        r("GL", "Greenland", MWL, ISNA),
        // Central America and the Caribbean
        r("GT", "Guatemala", ISNA, MWL),
        r("BZ", "Belize", ISNA, MWL),
        r("SV", "El Salvador", ISNA, MWL),
        r("HN", "Honduras", ISNA, MWL),
        r("NI", "Nicaragua", ISNA, MWL),
        r("CR", "Costa Rica", ISNA, MWL),
        r("PA", "Panama", ISNA, MWL),
        r("CU", "Cuba", ISNA, MWL),
        r("JM", "Jamaica", ISNA, MWL),
        r("HT", "Haiti", ISNA, MWL),
        r("DO", "Dominican Republic", ISNA, MWL),
        r("PR", "Puerto Rico", ISNA, MWL),
        r("TT", "Trinidad and Tobago", ISNA, MWL),
        r("BS", "Bahamas", ISNA, MWL),
        r("BB", "Barbados", ISNA, MWL),
        // South America
        r("BR", "Brazil", MWL, ISNA),
        r("AR", "Argentina", MWL, ISNA),
        r("CL", "Chile", MWL, ISNA),
        r("CO", "Colombia", MWL, ISNA),
        r("PE", "Peru", MWL, ISNA),
        r("VE", "Venezuela", MWL, ISNA),
        r("EC", "Ecuador", MWL, ISNA),
        r("BO", "Bolivia", MWL, ISNA),
        r("PY", "Paraguay", MWL, ISNA),
        r("UY", "Uruguay", MWL, ISNA),
        r("GY", "Guyana", MWL, ISNA),
        r("SR", "Suriname", MWL, ISNA),
        // Europe
        r("GB", "United Kingdom", MWL, ISNA, KARACHI, hanafi = true, note = "Many UK mosques follow a local timetable."),
        r("IE", "Ireland", MWL, ISNA),
        r("FR", "France", MWL, EGYPTIAN),
        r("DE", "Germany", MWL, EGYPTIAN),
        r("NL", "Netherlands", MWL, EGYPTIAN),
        r("BE", "Belgium", MWL, EGYPTIAN),
        r("LU", "Luxembourg", MWL),
        r("CH", "Switzerland", MWL, EGYPTIAN),
        r("AT", "Austria", MWL, EGYPTIAN),
        r("LI", "Liechtenstein", MWL),
        r("IT", "Italy", MWL, EGYPTIAN),
        r("ES", "Spain", MWL, EGYPTIAN),
        r("PT", "Portugal", MWL, EGYPTIAN),
        r("AD", "Andorra", MWL),
        r("MC", "Monaco", MWL),
        r("SM", "San Marino", MWL),
        r("VA", "Vatican City", MWL),
        r("MT", "Malta", MWL),
        r("GR", "Greece", MWL, EGYPTIAN),
        r("AL", "Albania", MWL, EGYPTIAN, hanafi = true),
        r("XK", "Kosovo", MWL, EGYPTIAN, hanafi = true),
        r("MK", "North Macedonia", MWL, EGYPTIAN, hanafi = true),
        r("BA", "Bosnia and Herzegovina", MWL, EGYPTIAN, hanafi = true),
        r("ME", "Montenegro", MWL),
        r("RS", "Serbia", MWL),
        r("HR", "Croatia", MWL),
        r("SI", "Slovenia", MWL),
        r("BG", "Bulgaria", MWL, hanafi = true),
        r("RO", "Romania", MWL),
        r("MD", "Moldova", MWL),
        r("HU", "Hungary", MWL),
        r("SK", "Slovakia", MWL),
        r("CZ", "Czechia", MWL),
        r("PL", "Poland", MWL),
        r("UA", "Ukraine", MWL, hanafi = true),
        r("BY", "Belarus", MWL),
        r("LT", "Lithuania", MWL),
        r("LV", "Latvia", MWL),
        r("EE", "Estonia", MWL),
        r("RU", "Russia", MWL, KARACHI, hanafi = true),
        r("SE", "Sweden", MWL, ISNA, note = HIGH_LATITUDE),
        r("NO", "Norway", MWL, ISNA, note = HIGH_LATITUDE),
        r("DK", "Denmark", MWL, ISNA),
        r("FI", "Finland", MWL, ISNA, note = HIGH_LATITUDE),
        r("IS", "Iceland", MWL, ISNA, note = HIGH_LATITUDE),
        // Sub-Saharan Africa
        r("NG", "Nigeria", MWL, EGYPTIAN),
        r("NE", "Niger", MWL, EGYPTIAN),
        r("ML", "Mali", MWL, EGYPTIAN),
        r("SN", "Senegal", MWL, EGYPTIAN),
        r("GM", "Gambia", MWL, EGYPTIAN),
        r("GN", "Guinea", MWL, EGYPTIAN),
        r("GW", "Guinea-Bissau", MWL, EGYPTIAN),
        r("SL", "Sierra Leone", MWL, EGYPTIAN),
        r("LR", "Liberia", MWL, EGYPTIAN),
        r("CI", "Ivory Coast", MWL, EGYPTIAN),
        r("BF", "Burkina Faso", MWL, EGYPTIAN),
        r("GH", "Ghana", MWL, EGYPTIAN),
        r("TG", "Togo", MWL, EGYPTIAN),
        r("BJ", "Benin", MWL, EGYPTIAN),
        r("CM", "Cameroon", MWL, EGYPTIAN),
        r("TD", "Chad", MWL, EGYPTIAN),
        r("CF", "Central African Republic", MWL, EGYPTIAN),
        r("GA", "Gabon", MWL, EGYPTIAN),
        r("CG", "Republic of the Congo", MWL, EGYPTIAN),
        r("CD", "DR Congo", MWL, EGYPTIAN),
        r("GQ", "Equatorial Guinea", MWL),
        r("CV", "Cape Verde", MWL),
        r("ST", "Sao Tome and Principe", MWL),
        r("ET", "Ethiopia", MWL, EGYPTIAN),
        r("ER", "Eritrea", MWL, EGYPTIAN),
        r("DJ", "Djibouti", MWL, GULF),
        r("SO", "Somalia", MWL, EGYPTIAN),
        r("KE", "Kenya", MWL, EGYPTIAN, KARACHI),
        r("TZ", "Tanzania", MWL, EGYPTIAN),
        r("UG", "Uganda", MWL, EGYPTIAN),
        r("RW", "Rwanda", MWL, EGYPTIAN),
        r("BI", "Burundi", MWL, EGYPTIAN),
        r("MZ", "Mozambique", MWL, EGYPTIAN),
        r("MW", "Malawi", MWL, EGYPTIAN),
        r("ZM", "Zambia", MWL, EGYPTIAN),
        r("ZW", "Zimbabwe", MWL, EGYPTIAN),
        r("AO", "Angola", MWL),
        r("NA", "Namibia", MWL),
        r("BW", "Botswana", MWL),
        r("ZA", "South Africa", MWL, KARACHI, hanafi = true),
        r("LS", "Lesotho", MWL),
        r("SZ", "Eswatini", MWL),
        r("MG", "Madagascar", MWL, EGYPTIAN),
        r("MU", "Mauritius", MWL, KARACHI),
        r("SC", "Seychelles", MWL),
        r("KM", "Comoros", MWL, EGYPTIAN),
        // Oceania
        r("AU", "Australia", MWL, ISNA, KARACHI),
        r("NZ", "New Zealand", MWL, ISNA),
        r("FJ", "Fiji", MWL, KARACHI),
        r("PG", "Papua New Guinea", MWL),
        r("SB", "Solomon Islands", MWL),
        r("VU", "Vanuatu", MWL),
        r("WS", "Samoa", MWL),
        r("TO", "Tonga", MWL)
    ).sortedBy { it.name }

    private val byCodeMap: Map<String, RegionInfo> = all.associateBy { it.code }

    fun byCode(code: String?): RegionInfo? = code?.uppercase()?.let(byCodeMap::get)
}
